// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package pgstore

import (
	"context"

	"github.com/google/uuid"
)

const getRoom = `-- name: GetRoom :one
SELECT 
    "id"
FROM
    rooms 
WHERE 
    id = $1
`

func (q *Queries) GetRoom(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getRoom, id)
	err := row.Scan(&id)
	return id, err
}
